[project]
version = "2.4.1"
icon = "https://avatars.githubusercontent.com/in/214508"
icon_width = "100px"

[variables]
information = [
	"IJsblokje is my co-pilot for GitHub operations! It is able to:\n",
	"- ðŸ·ï¸ Label PRs automatically according to the conventional commit types",
	"- ðŸ”ƒ Sync labels across mutliple repositories with the ability to add repository specific ones too",
	"- ðŸ”” Automatically adds a [GitCord](https://github.com/ijskoud/gitcord) webhook url to the webhooks everytime a repository is created and toggles it depending on the visibility state",
	"- ðŸ—žï¸ Syncs the readme's of multiple repositories using a config (readme.ijsblokje.toml) and a base readme (which is located at your own account repository -> ijsKoud/ijsKoud)",
	"- ðŸŽ‰ Releases a new version with automatic changelog generation (This can be done via the Discord bot integration)"
]
installation = [
  "Docker is required to host this app yourself. To install and run the GitHub app first pull the image using `docker pull ghcr.io/ijskoud/ijsblokje:github-bot` and after that run it using `docker run --name=ijsblokje-github-bot -v ~/.env:/ijsblokje/.env -d ghcr.io/ijskoud/ijsblokje:github-bot`, you can do the same with the Discord bot.",
	"Alternatively if you would like to use both the GitHub app and Discord bot you can use the provided `docker-compose.yml` file to install it. Simply copy the file to a directory on your pc/server, add the required `.env` files (examples are in the designated app directories) and run `docker-compose up`",
	"\n{variables.credits}"
]
credits = ["## Credits", "The logo was created using the <a href='https://www.freepik.com/vectors/melting-ice'>Melting ice vector created by freepik</a>"]